# Generated by Django 2.2.6 on 2019-11-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayname',
            name='day_name',
            field=models.CharField(choices=[('PN', 'Poniedziałek'), ('WT', 'Wtorek'), ('ŚR', 'Środa'), ('CZW', 'Czwartek'), ('PT', 'Piątek'), ('SB', 'Sobota'), ('ND', 'Niedziela')], max_length=3),
        ),
    ]
