# Generated by Django 2.2.6 on 2019-11-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeplan',
            name='meal_name',
            field=models.CharField(max_length=255),
        ),
    ]
