# Generated by Django 2.2.6 on 2019-11-11 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_auto_20191111_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeplan',
            old_name='day_name_id',
            new_name='day_name',
        ),
        migrations.RenameField(
            model_name='recipeplan',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='recipeplan',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
