# Generated by Django 2.2.6 on 2019-11-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_auto_20191112_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayname',
            name='order',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], unique=True),
        ),
    ]
