# Generated by Django 2.2.6 on 2019-11-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0006_auto_20191112_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='przykladowa instrukcja'),
            preserve_default=False,
        ),
    ]
